name: Lint Frontend

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check format with Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_version: '^2.2.5'
