name: Lint Frontend

on:
  push:
    branches: ['master']
    paths:
      - 'client/**'
  pull_request:
    branches: ['master']
    paths:
      - 'client/**'

jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i -w client
      - name: Check code with ESLint
        run: npm run lint -w client
