name: Lint Frontend

on:
    push:
        branches: ['master']
        paths:
            - 'client/**'
    pull_request:
        branches: ['master']
        paths:
            - 'client/**'

jobs:
    check-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm i
              working-directory: ./client
            - name: Check format with Prettier
              run: npx prettier -c .
              working-directory: ./client
            - name: Check code with ESLint
              run: npm run lint
              working-directory: ./client
